#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="D2009")]
	public partial class clientDynDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertRM00101(RM00101 instance);
    partial void UpdateRM00101(RM00101 instance);
    partial void DeleteRM00101(RM00101 instance);
    #endregion
		
		public clientDynDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["D2009ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public clientDynDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clientDynDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clientDynDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clientDynDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RM00101> RM00101
		{
			get
			{
				return this.GetTable<RM00101>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RM00101")]
	public partial class RM00101 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CUSTNMBR;
		
		private string _CUSTNAME;
		
		private string _CUSTCLAS;
		
		private string _CPRCSTNM;
		
		private string _CNTCPRSN;
		
		private string _STMTNAME;
		
		private string _SHRTNAME;
		
		private string _ADRSCODE;
		
		private string _UPSZONE;
		
		private string _SHIPMTHD;
		
		private string _TAXSCHID;
		
		private string _ADDRESS1;
		
		private string _ADDRESS2;
		
		private string _ADDRESS3;
		
		private string _COUNTRY;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _ZIP;
		
		private string _PHONE1;
		
		private string _PHONE2;
		
		private string _PHONE3;
		
		private string _FAX;
		
		private string _PRBTADCD;
		
		private string _PRSTADCD;
		
		private string _STADDRCD;
		
		private string _SLPRSNID;
		
		private string _CHEKBKID;
		
		private string _PYMTRMID;
		
		private short _CRLMTTYP;
		
		private decimal _CRLMTAMT;
		
		private short _CRLMTPER;
		
		private decimal _CRLMTPAM;
		
		private string _CURNCYID;
		
		private string _RATETPID;
		
		private short _CUSTDISC;
		
		private string _PRCLEVEL;
		
		private short _MINPYTYP;
		
		private decimal _MINPYDLR;
		
		private short _MINPYPCT;
		
		private short _FNCHATYP;
		
		private short _FNCHPCNT;
		
		private decimal _FINCHDLR;
		
		private short _MXWOFTYP;
		
		private decimal _MXWROFAM;
		
		private string _COMMENT1;
		
		private string _COMMENT2;
		
		private string _USERDEF1;
		
		private string _USERDEF2;
		
		private string _TAXEXMT1;
		
		private string _TAXEXMT2;
		
		private string _TXRGNNUM;
		
		private short _BALNCTYP;
		
		private short _STMTCYCL;
		
		private string _BANKNAME;
		
		private string _BNKBRNCH;
		
		private string _SALSTERR;
		
		private short _DEFCACTY;
		
		private int _RMCSHACC;
		
		private int _RMARACC;
		
		private int _RMSLSACC;
		
		private int _RMIVACC;
		
		private int _RMCOSACC;
		
		private int _RMTAKACC;
		
		private int _RMAVACC;
		
		private int _RMFCGACC;
		
		private int _RMWRACC;
		
		private int _RMSORACC;
		
		private System.DateTime _FRSTINDT;
		
		private byte _INACTIVE;
		
		private byte _HOLD;
		
		private string _CRCARDID;
		
		private string _CRCRDNUM;
		
		private System.DateTime _CCRDXPDT;
		
		private byte _KPDSTHST;
		
		private byte _KPCALHST;
		
		private byte _KPERHIST;
		
		private byte _KPTRXHST;
		
		private decimal _NOTEINDX;
		
		private System.DateTime _CREATDDT;
		
		private System.DateTime _MODIFDT;
		
		private byte _Revalue_Customer;
		
		private short _Post_Results_To;
		
		private string _FINCHID;
		
		private string _GOVCRPID;
		
		private string _GOVINDID;
		
		private short _DISGRPER;
		
		private short _DUEGRPER;
		
		private string _DOCFMTID;
		
		private byte _Send_Email_Statements;
		
		private short _USERLANG;
		
		private string _GPSFOINTEGRATIONID;
		
		private short _INTEGRATIONSOURCE;
		
		private string _INTEGRATIONID;
		
		private short _ORDERFULFILLDEFAULT;
		
		private short _CUSTPRIORITY;
		
		private string _CCode;
		
		private string _DECLID;
		
		private int _RMOvrpymtWrtoffAcctIdx;
		
		private byte _SHIPCOMPLETE;
		
		private byte _CBVAT;
		
		private byte _INCLUDEINDP;
		
		private System.DateTime _DEX_ROW_TS;
		
		private int _DEX_ROW_ID;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUSTNMBRChanging(string value);
    partial void OnCUSTNMBRChanged();
    partial void OnCUSTNAMEChanging(string value);
    partial void OnCUSTNAMEChanged();
    partial void OnCUSTCLASChanging(string value);
    partial void OnCUSTCLASChanged();
    partial void OnCPRCSTNMChanging(string value);
    partial void OnCPRCSTNMChanged();
    partial void OnCNTCPRSNChanging(string value);
    partial void OnCNTCPRSNChanged();
    partial void OnSTMTNAMEChanging(string value);
    partial void OnSTMTNAMEChanged();
    partial void OnSHRTNAMEChanging(string value);
    partial void OnSHRTNAMEChanged();
    partial void OnADRSCODEChanging(string value);
    partial void OnADRSCODEChanged();
    partial void OnUPSZONEChanging(string value);
    partial void OnUPSZONEChanged();
    partial void OnSHIPMTHDChanging(string value);
    partial void OnSHIPMTHDChanged();
    partial void OnTAXSCHIDChanging(string value);
    partial void OnTAXSCHIDChanged();
    partial void OnADDRESS1Changing(string value);
    partial void OnADDRESS1Changed();
    partial void OnADDRESS2Changing(string value);
    partial void OnADDRESS2Changed();
    partial void OnADDRESS3Changing(string value);
    partial void OnADDRESS3Changed();
    partial void OnCOUNTRYChanging(string value);
    partial void OnCOUNTRYChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnZIPChanging(string value);
    partial void OnZIPChanged();
    partial void OnPHONE1Changing(string value);
    partial void OnPHONE1Changed();
    partial void OnPHONE2Changing(string value);
    partial void OnPHONE2Changed();
    partial void OnPHONE3Changing(string value);
    partial void OnPHONE3Changed();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnPRBTADCDChanging(string value);
    partial void OnPRBTADCDChanged();
    partial void OnPRSTADCDChanging(string value);
    partial void OnPRSTADCDChanged();
    partial void OnSTADDRCDChanging(string value);
    partial void OnSTADDRCDChanged();
    partial void OnSLPRSNIDChanging(string value);
    partial void OnSLPRSNIDChanged();
    partial void OnCHEKBKIDChanging(string value);
    partial void OnCHEKBKIDChanged();
    partial void OnPYMTRMIDChanging(string value);
    partial void OnPYMTRMIDChanged();
    partial void OnCRLMTTYPChanging(short value);
    partial void OnCRLMTTYPChanged();
    partial void OnCRLMTAMTChanging(decimal value);
    partial void OnCRLMTAMTChanged();
    partial void OnCRLMTPERChanging(short value);
    partial void OnCRLMTPERChanged();
    partial void OnCRLMTPAMChanging(decimal value);
    partial void OnCRLMTPAMChanged();
    partial void OnCURNCYIDChanging(string value);
    partial void OnCURNCYIDChanged();
    partial void OnRATETPIDChanging(string value);
    partial void OnRATETPIDChanged();
    partial void OnCUSTDISCChanging(short value);
    partial void OnCUSTDISCChanged();
    partial void OnPRCLEVELChanging(string value);
    partial void OnPRCLEVELChanged();
    partial void OnMINPYTYPChanging(short value);
    partial void OnMINPYTYPChanged();
    partial void OnMINPYDLRChanging(decimal value);
    partial void OnMINPYDLRChanged();
    partial void OnMINPYPCTChanging(short value);
    partial void OnMINPYPCTChanged();
    partial void OnFNCHATYPChanging(short value);
    partial void OnFNCHATYPChanged();
    partial void OnFNCHPCNTChanging(short value);
    partial void OnFNCHPCNTChanged();
    partial void OnFINCHDLRChanging(decimal value);
    partial void OnFINCHDLRChanged();
    partial void OnMXWOFTYPChanging(short value);
    partial void OnMXWOFTYPChanged();
    partial void OnMXWROFAMChanging(decimal value);
    partial void OnMXWROFAMChanged();
    partial void OnCOMMENT1Changing(string value);
    partial void OnCOMMENT1Changed();
    partial void OnCOMMENT2Changing(string value);
    partial void OnCOMMENT2Changed();
    partial void OnUSERDEF1Changing(string value);
    partial void OnUSERDEF1Changed();
    partial void OnUSERDEF2Changing(string value);
    partial void OnUSERDEF2Changed();
    partial void OnTAXEXMT1Changing(string value);
    partial void OnTAXEXMT1Changed();
    partial void OnTAXEXMT2Changing(string value);
    partial void OnTAXEXMT2Changed();
    partial void OnTXRGNNUMChanging(string value);
    partial void OnTXRGNNUMChanged();
    partial void OnBALNCTYPChanging(short value);
    partial void OnBALNCTYPChanged();
    partial void OnSTMTCYCLChanging(short value);
    partial void OnSTMTCYCLChanged();
    partial void OnBANKNAMEChanging(string value);
    partial void OnBANKNAMEChanged();
    partial void OnBNKBRNCHChanging(string value);
    partial void OnBNKBRNCHChanged();
    partial void OnSALSTERRChanging(string value);
    partial void OnSALSTERRChanged();
    partial void OnDEFCACTYChanging(short value);
    partial void OnDEFCACTYChanged();
    partial void OnRMCSHACCChanging(int value);
    partial void OnRMCSHACCChanged();
    partial void OnRMARACCChanging(int value);
    partial void OnRMARACCChanged();
    partial void OnRMSLSACCChanging(int value);
    partial void OnRMSLSACCChanged();
    partial void OnRMIVACCChanging(int value);
    partial void OnRMIVACCChanged();
    partial void OnRMCOSACCChanging(int value);
    partial void OnRMCOSACCChanged();
    partial void OnRMTAKACCChanging(int value);
    partial void OnRMTAKACCChanged();
    partial void OnRMAVACCChanging(int value);
    partial void OnRMAVACCChanged();
    partial void OnRMFCGACCChanging(int value);
    partial void OnRMFCGACCChanged();
    partial void OnRMWRACCChanging(int value);
    partial void OnRMWRACCChanged();
    partial void OnRMSORACCChanging(int value);
    partial void OnRMSORACCChanged();
    partial void OnFRSTINDTChanging(System.DateTime value);
    partial void OnFRSTINDTChanged();
    partial void OnINACTIVEChanging(byte value);
    partial void OnINACTIVEChanged();
    partial void OnHOLDChanging(byte value);
    partial void OnHOLDChanged();
    partial void OnCRCARDIDChanging(string value);
    partial void OnCRCARDIDChanged();
    partial void OnCRCRDNUMChanging(string value);
    partial void OnCRCRDNUMChanged();
    partial void OnCCRDXPDTChanging(System.DateTime value);
    partial void OnCCRDXPDTChanged();
    partial void OnKPDSTHSTChanging(byte value);
    partial void OnKPDSTHSTChanged();
    partial void OnKPCALHSTChanging(byte value);
    partial void OnKPCALHSTChanged();
    partial void OnKPERHISTChanging(byte value);
    partial void OnKPERHISTChanged();
    partial void OnKPTRXHSTChanging(byte value);
    partial void OnKPTRXHSTChanged();
    partial void OnNOTEINDXChanging(decimal value);
    partial void OnNOTEINDXChanged();
    partial void OnCREATDDTChanging(System.DateTime value);
    partial void OnCREATDDTChanged();
    partial void OnMODIFDTChanging(System.DateTime value);
    partial void OnMODIFDTChanged();
    partial void OnRevalue_CustomerChanging(byte value);
    partial void OnRevalue_CustomerChanged();
    partial void OnPost_Results_ToChanging(short value);
    partial void OnPost_Results_ToChanged();
    partial void OnFINCHIDChanging(string value);
    partial void OnFINCHIDChanged();
    partial void OnGOVCRPIDChanging(string value);
    partial void OnGOVCRPIDChanged();
    partial void OnGOVINDIDChanging(string value);
    partial void OnGOVINDIDChanged();
    partial void OnDISGRPERChanging(short value);
    partial void OnDISGRPERChanged();
    partial void OnDUEGRPERChanging(short value);
    partial void OnDUEGRPERChanged();
    partial void OnDOCFMTIDChanging(string value);
    partial void OnDOCFMTIDChanged();
    partial void OnSend_Email_StatementsChanging(byte value);
    partial void OnSend_Email_StatementsChanged();
    partial void OnUSERLANGChanging(short value);
    partial void OnUSERLANGChanged();
    partial void OnGPSFOINTEGRATIONIDChanging(string value);
    partial void OnGPSFOINTEGRATIONIDChanged();
    partial void OnINTEGRATIONSOURCEChanging(short value);
    partial void OnINTEGRATIONSOURCEChanged();
    partial void OnINTEGRATIONIDChanging(string value);
    partial void OnINTEGRATIONIDChanged();
    partial void OnORDERFULFILLDEFAULTChanging(short value);
    partial void OnORDERFULFILLDEFAULTChanged();
    partial void OnCUSTPRIORITYChanging(short value);
    partial void OnCUSTPRIORITYChanged();
    partial void OnCCodeChanging(string value);
    partial void OnCCodeChanged();
    partial void OnDECLIDChanging(string value);
    partial void OnDECLIDChanged();
    partial void OnRMOvrpymtWrtoffAcctIdxChanging(int value);
    partial void OnRMOvrpymtWrtoffAcctIdxChanged();
    partial void OnSHIPCOMPLETEChanging(byte value);
    partial void OnSHIPCOMPLETEChanged();
    partial void OnCBVATChanging(byte value);
    partial void OnCBVATChanged();
    partial void OnINCLUDEINDPChanging(byte value);
    partial void OnINCLUDEINDPChanged();
    partial void OnDEX_ROW_TSChanging(System.DateTime value);
    partial void OnDEX_ROW_TSChanged();
    partial void OnDEX_ROW_IDChanging(int value);
    partial void OnDEX_ROW_IDChanged();
    #endregion
		
		public RM00101()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTNMBR", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CUSTNMBR
		{
			get
			{
				return this._CUSTNMBR;
			}
			set
			{
				if ((this._CUSTNMBR != value))
				{
					this.OnCUSTNMBRChanging(value);
					this.SendPropertyChanging();
					this._CUSTNMBR = value;
					this.SendPropertyChanged("CUSTNMBR");
					this.OnCUSTNMBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTNAME", DbType="Char(65) NOT NULL", CanBeNull=false)]
		public string CUSTNAME
		{
			get
			{
				return this._CUSTNAME;
			}
			set
			{
				if ((this._CUSTNAME != value))
				{
					this.OnCUSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTNAME = value;
					this.SendPropertyChanged("CUSTNAME");
					this.OnCUSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTCLAS", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string CUSTCLAS
		{
			get
			{
				return this._CUSTCLAS;
			}
			set
			{
				if ((this._CUSTCLAS != value))
				{
					this.OnCUSTCLASChanging(value);
					this.SendPropertyChanging();
					this._CUSTCLAS = value;
					this.SendPropertyChanged("CUSTCLAS");
					this.OnCUSTCLASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPRCSTNM", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string CPRCSTNM
		{
			get
			{
				return this._CPRCSTNM;
			}
			set
			{
				if ((this._CPRCSTNM != value))
				{
					this.OnCPRCSTNMChanging(value);
					this.SendPropertyChanging();
					this._CPRCSTNM = value;
					this.SendPropertyChanged("CPRCSTNM");
					this.OnCPRCSTNMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNTCPRSN", DbType="Char(61) NOT NULL", CanBeNull=false)]
		public string CNTCPRSN
		{
			get
			{
				return this._CNTCPRSN;
			}
			set
			{
				if ((this._CNTCPRSN != value))
				{
					this.OnCNTCPRSNChanging(value);
					this.SendPropertyChanging();
					this._CNTCPRSN = value;
					this.SendPropertyChanged("CNTCPRSN");
					this.OnCNTCPRSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STMTNAME", DbType="Char(65) NOT NULL", CanBeNull=false)]
		public string STMTNAME
		{
			get
			{
				return this._STMTNAME;
			}
			set
			{
				if ((this._STMTNAME != value))
				{
					this.OnSTMTNAMEChanging(value);
					this.SendPropertyChanging();
					this._STMTNAME = value;
					this.SendPropertyChanged("STMTNAME");
					this.OnSTMTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHRTNAME", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string SHRTNAME
		{
			get
			{
				return this._SHRTNAME;
			}
			set
			{
				if ((this._SHRTNAME != value))
				{
					this.OnSHRTNAMEChanging(value);
					this.SendPropertyChanging();
					this._SHRTNAME = value;
					this.SendPropertyChanged("SHRTNAME");
					this.OnSHRTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRSCODE", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string ADRSCODE
		{
			get
			{
				return this._ADRSCODE;
			}
			set
			{
				if ((this._ADRSCODE != value))
				{
					this.OnADRSCODEChanging(value);
					this.SendPropertyChanging();
					this._ADRSCODE = value;
					this.SendPropertyChanged("ADRSCODE");
					this.OnADRSCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPSZONE", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string UPSZONE
		{
			get
			{
				return this._UPSZONE;
			}
			set
			{
				if ((this._UPSZONE != value))
				{
					this.OnUPSZONEChanging(value);
					this.SendPropertyChanging();
					this._UPSZONE = value;
					this.SendPropertyChanged("UPSZONE");
					this.OnUPSZONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIPMTHD", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string SHIPMTHD
		{
			get
			{
				return this._SHIPMTHD;
			}
			set
			{
				if ((this._SHIPMTHD != value))
				{
					this.OnSHIPMTHDChanging(value);
					this.SendPropertyChanging();
					this._SHIPMTHD = value;
					this.SendPropertyChanged("SHIPMTHD");
					this.OnSHIPMTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXSCHID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string TAXSCHID
		{
			get
			{
				return this._TAXSCHID;
			}
			set
			{
				if ((this._TAXSCHID != value))
				{
					this.OnTAXSCHIDChanging(value);
					this.SendPropertyChanging();
					this._TAXSCHID = value;
					this.SendPropertyChanged("TAXSCHID");
					this.OnTAXSCHIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS1", DbType="Char(61) NOT NULL", CanBeNull=false)]
		public string ADDRESS1
		{
			get
			{
				return this._ADDRESS1;
			}
			set
			{
				if ((this._ADDRESS1 != value))
				{
					this.OnADDRESS1Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS1 = value;
					this.SendPropertyChanged("ADDRESS1");
					this.OnADDRESS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS2", DbType="Char(61) NOT NULL", CanBeNull=false)]
		public string ADDRESS2
		{
			get
			{
				return this._ADDRESS2;
			}
			set
			{
				if ((this._ADDRESS2 != value))
				{
					this.OnADDRESS2Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS2 = value;
					this.SendPropertyChanged("ADDRESS2");
					this.OnADDRESS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS3", DbType="Char(61) NOT NULL", CanBeNull=false)]
		public string ADDRESS3
		{
			get
			{
				return this._ADDRESS3;
			}
			set
			{
				if ((this._ADDRESS3 != value))
				{
					this.OnADDRESS3Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS3 = value;
					this.SendPropertyChanged("ADDRESS3");
					this.OnADDRESS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="Char(61) NOT NULL", CanBeNull=false)]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this.OnCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._COUNTRY = value;
					this.SendPropertyChanged("COUNTRY");
					this.OnCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="Char(35) NOT NULL", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="Char(29) NOT NULL", CanBeNull=false)]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this.OnZIPChanging(value);
					this.SendPropertyChanging();
					this._ZIP = value;
					this.SendPropertyChanged("ZIP");
					this.OnZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE1", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string PHONE1
		{
			get
			{
				return this._PHONE1;
			}
			set
			{
				if ((this._PHONE1 != value))
				{
					this.OnPHONE1Changing(value);
					this.SendPropertyChanging();
					this._PHONE1 = value;
					this.SendPropertyChanged("PHONE1");
					this.OnPHONE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE2", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string PHONE2
		{
			get
			{
				return this._PHONE2;
			}
			set
			{
				if ((this._PHONE2 != value))
				{
					this.OnPHONE2Changing(value);
					this.SendPropertyChanging();
					this._PHONE2 = value;
					this.SendPropertyChanged("PHONE2");
					this.OnPHONE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONE3", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string PHONE3
		{
			get
			{
				return this._PHONE3;
			}
			set
			{
				if ((this._PHONE3 != value))
				{
					this.OnPHONE3Changing(value);
					this.SendPropertyChanging();
					this._PHONE3 = value;
					this.SendPropertyChanged("PHONE3");
					this.OnPHONE3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRBTADCD", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string PRBTADCD
		{
			get
			{
				return this._PRBTADCD;
			}
			set
			{
				if ((this._PRBTADCD != value))
				{
					this.OnPRBTADCDChanging(value);
					this.SendPropertyChanging();
					this._PRBTADCD = value;
					this.SendPropertyChanged("PRBTADCD");
					this.OnPRBTADCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRSTADCD", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string PRSTADCD
		{
			get
			{
				return this._PRSTADCD;
			}
			set
			{
				if ((this._PRSTADCD != value))
				{
					this.OnPRSTADCDChanging(value);
					this.SendPropertyChanging();
					this._PRSTADCD = value;
					this.SendPropertyChanged("PRSTADCD");
					this.OnPRSTADCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STADDRCD", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string STADDRCD
		{
			get
			{
				return this._STADDRCD;
			}
			set
			{
				if ((this._STADDRCD != value))
				{
					this.OnSTADDRCDChanging(value);
					this.SendPropertyChanging();
					this._STADDRCD = value;
					this.SendPropertyChanged("STADDRCD");
					this.OnSTADDRCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLPRSNID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string SLPRSNID
		{
			get
			{
				return this._SLPRSNID;
			}
			set
			{
				if ((this._SLPRSNID != value))
				{
					this.OnSLPRSNIDChanging(value);
					this.SendPropertyChanging();
					this._SLPRSNID = value;
					this.SendPropertyChanged("SLPRSNID");
					this.OnSLPRSNIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHEKBKID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string CHEKBKID
		{
			get
			{
				return this._CHEKBKID;
			}
			set
			{
				if ((this._CHEKBKID != value))
				{
					this.OnCHEKBKIDChanging(value);
					this.SendPropertyChanging();
					this._CHEKBKID = value;
					this.SendPropertyChanged("CHEKBKID");
					this.OnCHEKBKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PYMTRMID", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string PYMTRMID
		{
			get
			{
				return this._PYMTRMID;
			}
			set
			{
				if ((this._PYMTRMID != value))
				{
					this.OnPYMTRMIDChanging(value);
					this.SendPropertyChanging();
					this._PYMTRMID = value;
					this.SendPropertyChanged("PYMTRMID");
					this.OnPYMTRMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRLMTTYP", DbType="SmallInt NOT NULL")]
		public short CRLMTTYP
		{
			get
			{
				return this._CRLMTTYP;
			}
			set
			{
				if ((this._CRLMTTYP != value))
				{
					this.OnCRLMTTYPChanging(value);
					this.SendPropertyChanging();
					this._CRLMTTYP = value;
					this.SendPropertyChanged("CRLMTTYP");
					this.OnCRLMTTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRLMTAMT", DbType="Decimal(19,5) NOT NULL")]
		public decimal CRLMTAMT
		{
			get
			{
				return this._CRLMTAMT;
			}
			set
			{
				if ((this._CRLMTAMT != value))
				{
					this.OnCRLMTAMTChanging(value);
					this.SendPropertyChanging();
					this._CRLMTAMT = value;
					this.SendPropertyChanged("CRLMTAMT");
					this.OnCRLMTAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRLMTPER", DbType="SmallInt NOT NULL")]
		public short CRLMTPER
		{
			get
			{
				return this._CRLMTPER;
			}
			set
			{
				if ((this._CRLMTPER != value))
				{
					this.OnCRLMTPERChanging(value);
					this.SendPropertyChanging();
					this._CRLMTPER = value;
					this.SendPropertyChanged("CRLMTPER");
					this.OnCRLMTPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRLMTPAM", DbType="Decimal(19,5) NOT NULL")]
		public decimal CRLMTPAM
		{
			get
			{
				return this._CRLMTPAM;
			}
			set
			{
				if ((this._CRLMTPAM != value))
				{
					this.OnCRLMTPAMChanging(value);
					this.SendPropertyChanging();
					this._CRLMTPAM = value;
					this.SendPropertyChanged("CRLMTPAM");
					this.OnCRLMTPAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURNCYID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string CURNCYID
		{
			get
			{
				return this._CURNCYID;
			}
			set
			{
				if ((this._CURNCYID != value))
				{
					this.OnCURNCYIDChanging(value);
					this.SendPropertyChanging();
					this._CURNCYID = value;
					this.SendPropertyChanged("CURNCYID");
					this.OnCURNCYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RATETPID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string RATETPID
		{
			get
			{
				return this._RATETPID;
			}
			set
			{
				if ((this._RATETPID != value))
				{
					this.OnRATETPIDChanging(value);
					this.SendPropertyChanging();
					this._RATETPID = value;
					this.SendPropertyChanged("RATETPID");
					this.OnRATETPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTDISC", DbType="SmallInt NOT NULL")]
		public short CUSTDISC
		{
			get
			{
				return this._CUSTDISC;
			}
			set
			{
				if ((this._CUSTDISC != value))
				{
					this.OnCUSTDISCChanging(value);
					this.SendPropertyChanging();
					this._CUSTDISC = value;
					this.SendPropertyChanged("CUSTDISC");
					this.OnCUSTDISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRCLEVEL", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string PRCLEVEL
		{
			get
			{
				return this._PRCLEVEL;
			}
			set
			{
				if ((this._PRCLEVEL != value))
				{
					this.OnPRCLEVELChanging(value);
					this.SendPropertyChanging();
					this._PRCLEVEL = value;
					this.SendPropertyChanged("PRCLEVEL");
					this.OnPRCLEVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MINPYTYP", DbType="SmallInt NOT NULL")]
		public short MINPYTYP
		{
			get
			{
				return this._MINPYTYP;
			}
			set
			{
				if ((this._MINPYTYP != value))
				{
					this.OnMINPYTYPChanging(value);
					this.SendPropertyChanging();
					this._MINPYTYP = value;
					this.SendPropertyChanged("MINPYTYP");
					this.OnMINPYTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MINPYDLR", DbType="Decimal(19,5) NOT NULL")]
		public decimal MINPYDLR
		{
			get
			{
				return this._MINPYDLR;
			}
			set
			{
				if ((this._MINPYDLR != value))
				{
					this.OnMINPYDLRChanging(value);
					this.SendPropertyChanging();
					this._MINPYDLR = value;
					this.SendPropertyChanged("MINPYDLR");
					this.OnMINPYDLRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MINPYPCT", DbType="SmallInt NOT NULL")]
		public short MINPYPCT
		{
			get
			{
				return this._MINPYPCT;
			}
			set
			{
				if ((this._MINPYPCT != value))
				{
					this.OnMINPYPCTChanging(value);
					this.SendPropertyChanging();
					this._MINPYPCT = value;
					this.SendPropertyChanged("MINPYPCT");
					this.OnMINPYPCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNCHATYP", DbType="SmallInt NOT NULL")]
		public short FNCHATYP
		{
			get
			{
				return this._FNCHATYP;
			}
			set
			{
				if ((this._FNCHATYP != value))
				{
					this.OnFNCHATYPChanging(value);
					this.SendPropertyChanging();
					this._FNCHATYP = value;
					this.SendPropertyChanged("FNCHATYP");
					this.OnFNCHATYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNCHPCNT", DbType="SmallInt NOT NULL")]
		public short FNCHPCNT
		{
			get
			{
				return this._FNCHPCNT;
			}
			set
			{
				if ((this._FNCHPCNT != value))
				{
					this.OnFNCHPCNTChanging(value);
					this.SendPropertyChanging();
					this._FNCHPCNT = value;
					this.SendPropertyChanged("FNCHPCNT");
					this.OnFNCHPCNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINCHDLR", DbType="Decimal(19,5) NOT NULL")]
		public decimal FINCHDLR
		{
			get
			{
				return this._FINCHDLR;
			}
			set
			{
				if ((this._FINCHDLR != value))
				{
					this.OnFINCHDLRChanging(value);
					this.SendPropertyChanging();
					this._FINCHDLR = value;
					this.SendPropertyChanged("FINCHDLR");
					this.OnFINCHDLRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MXWOFTYP", DbType="SmallInt NOT NULL")]
		public short MXWOFTYP
		{
			get
			{
				return this._MXWOFTYP;
			}
			set
			{
				if ((this._MXWOFTYP != value))
				{
					this.OnMXWOFTYPChanging(value);
					this.SendPropertyChanging();
					this._MXWOFTYP = value;
					this.SendPropertyChanged("MXWOFTYP");
					this.OnMXWOFTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MXWROFAM", DbType="Decimal(19,5) NOT NULL")]
		public decimal MXWROFAM
		{
			get
			{
				return this._MXWROFAM;
			}
			set
			{
				if ((this._MXWROFAM != value))
				{
					this.OnMXWROFAMChanging(value);
					this.SendPropertyChanging();
					this._MXWROFAM = value;
					this.SendPropertyChanged("MXWROFAM");
					this.OnMXWROFAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT1", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string COMMENT1
		{
			get
			{
				return this._COMMENT1;
			}
			set
			{
				if ((this._COMMENT1 != value))
				{
					this.OnCOMMENT1Changing(value);
					this.SendPropertyChanging();
					this._COMMENT1 = value;
					this.SendPropertyChanged("COMMENT1");
					this.OnCOMMENT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT2", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string COMMENT2
		{
			get
			{
				return this._COMMENT2;
			}
			set
			{
				if ((this._COMMENT2 != value))
				{
					this.OnCOMMENT2Changing(value);
					this.SendPropertyChanging();
					this._COMMENT2 = value;
					this.SendPropertyChanged("COMMENT2");
					this.OnCOMMENT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERDEF1", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string USERDEF1
		{
			get
			{
				return this._USERDEF1;
			}
			set
			{
				if ((this._USERDEF1 != value))
				{
					this.OnUSERDEF1Changing(value);
					this.SendPropertyChanging();
					this._USERDEF1 = value;
					this.SendPropertyChanged("USERDEF1");
					this.OnUSERDEF1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERDEF2", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string USERDEF2
		{
			get
			{
				return this._USERDEF2;
			}
			set
			{
				if ((this._USERDEF2 != value))
				{
					this.OnUSERDEF2Changing(value);
					this.SendPropertyChanging();
					this._USERDEF2 = value;
					this.SendPropertyChanged("USERDEF2");
					this.OnUSERDEF2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXEXMT1", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string TAXEXMT1
		{
			get
			{
				return this._TAXEXMT1;
			}
			set
			{
				if ((this._TAXEXMT1 != value))
				{
					this.OnTAXEXMT1Changing(value);
					this.SendPropertyChanging();
					this._TAXEXMT1 = value;
					this.SendPropertyChanged("TAXEXMT1");
					this.OnTAXEXMT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXEXMT2", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string TAXEXMT2
		{
			get
			{
				return this._TAXEXMT2;
			}
			set
			{
				if ((this._TAXEXMT2 != value))
				{
					this.OnTAXEXMT2Changing(value);
					this.SendPropertyChanging();
					this._TAXEXMT2 = value;
					this.SendPropertyChanged("TAXEXMT2");
					this.OnTAXEXMT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TXRGNNUM", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string TXRGNNUM
		{
			get
			{
				return this._TXRGNNUM;
			}
			set
			{
				if ((this._TXRGNNUM != value))
				{
					this.OnTXRGNNUMChanging(value);
					this.SendPropertyChanging();
					this._TXRGNNUM = value;
					this.SendPropertyChanged("TXRGNNUM");
					this.OnTXRGNNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BALNCTYP", DbType="SmallInt NOT NULL")]
		public short BALNCTYP
		{
			get
			{
				return this._BALNCTYP;
			}
			set
			{
				if ((this._BALNCTYP != value))
				{
					this.OnBALNCTYPChanging(value);
					this.SendPropertyChanging();
					this._BALNCTYP = value;
					this.SendPropertyChanged("BALNCTYP");
					this.OnBALNCTYPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STMTCYCL", DbType="SmallInt NOT NULL")]
		public short STMTCYCL
		{
			get
			{
				return this._STMTCYCL;
			}
			set
			{
				if ((this._STMTCYCL != value))
				{
					this.OnSTMTCYCLChanging(value);
					this.SendPropertyChanging();
					this._STMTCYCL = value;
					this.SendPropertyChanged("STMTCYCL");
					this.OnSTMTCYCLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNAME", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string BANKNAME
		{
			get
			{
				return this._BANKNAME;
			}
			set
			{
				if ((this._BANKNAME != value))
				{
					this.OnBANKNAMEChanging(value);
					this.SendPropertyChanging();
					this._BANKNAME = value;
					this.SendPropertyChanged("BANKNAME");
					this.OnBANKNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BNKBRNCH", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string BNKBRNCH
		{
			get
			{
				return this._BNKBRNCH;
			}
			set
			{
				if ((this._BNKBRNCH != value))
				{
					this.OnBNKBRNCHChanging(value);
					this.SendPropertyChanging();
					this._BNKBRNCH = value;
					this.SendPropertyChanged("BNKBRNCH");
					this.OnBNKBRNCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALSTERR", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string SALSTERR
		{
			get
			{
				return this._SALSTERR;
			}
			set
			{
				if ((this._SALSTERR != value))
				{
					this.OnSALSTERRChanging(value);
					this.SendPropertyChanging();
					this._SALSTERR = value;
					this.SendPropertyChanged("SALSTERR");
					this.OnSALSTERRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEFCACTY", DbType="SmallInt NOT NULL")]
		public short DEFCACTY
		{
			get
			{
				return this._DEFCACTY;
			}
			set
			{
				if ((this._DEFCACTY != value))
				{
					this.OnDEFCACTYChanging(value);
					this.SendPropertyChanging();
					this._DEFCACTY = value;
					this.SendPropertyChanged("DEFCACTY");
					this.OnDEFCACTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCSHACC", DbType="Int NOT NULL")]
		public int RMCSHACC
		{
			get
			{
				return this._RMCSHACC;
			}
			set
			{
				if ((this._RMCSHACC != value))
				{
					this.OnRMCSHACCChanging(value);
					this.SendPropertyChanging();
					this._RMCSHACC = value;
					this.SendPropertyChanged("RMCSHACC");
					this.OnRMCSHACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMARACC", DbType="Int NOT NULL")]
		public int RMARACC
		{
			get
			{
				return this._RMARACC;
			}
			set
			{
				if ((this._RMARACC != value))
				{
					this.OnRMARACCChanging(value);
					this.SendPropertyChanging();
					this._RMARACC = value;
					this.SendPropertyChanged("RMARACC");
					this.OnRMARACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMSLSACC", DbType="Int NOT NULL")]
		public int RMSLSACC
		{
			get
			{
				return this._RMSLSACC;
			}
			set
			{
				if ((this._RMSLSACC != value))
				{
					this.OnRMSLSACCChanging(value);
					this.SendPropertyChanging();
					this._RMSLSACC = value;
					this.SendPropertyChanged("RMSLSACC");
					this.OnRMSLSACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMIVACC", DbType="Int NOT NULL")]
		public int RMIVACC
		{
			get
			{
				return this._RMIVACC;
			}
			set
			{
				if ((this._RMIVACC != value))
				{
					this.OnRMIVACCChanging(value);
					this.SendPropertyChanging();
					this._RMIVACC = value;
					this.SendPropertyChanged("RMIVACC");
					this.OnRMIVACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMCOSACC", DbType="Int NOT NULL")]
		public int RMCOSACC
		{
			get
			{
				return this._RMCOSACC;
			}
			set
			{
				if ((this._RMCOSACC != value))
				{
					this.OnRMCOSACCChanging(value);
					this.SendPropertyChanging();
					this._RMCOSACC = value;
					this.SendPropertyChanged("RMCOSACC");
					this.OnRMCOSACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMTAKACC", DbType="Int NOT NULL")]
		public int RMTAKACC
		{
			get
			{
				return this._RMTAKACC;
			}
			set
			{
				if ((this._RMTAKACC != value))
				{
					this.OnRMTAKACCChanging(value);
					this.SendPropertyChanging();
					this._RMTAKACC = value;
					this.SendPropertyChanged("RMTAKACC");
					this.OnRMTAKACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMAVACC", DbType="Int NOT NULL")]
		public int RMAVACC
		{
			get
			{
				return this._RMAVACC;
			}
			set
			{
				if ((this._RMAVACC != value))
				{
					this.OnRMAVACCChanging(value);
					this.SendPropertyChanging();
					this._RMAVACC = value;
					this.SendPropertyChanged("RMAVACC");
					this.OnRMAVACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMFCGACC", DbType="Int NOT NULL")]
		public int RMFCGACC
		{
			get
			{
				return this._RMFCGACC;
			}
			set
			{
				if ((this._RMFCGACC != value))
				{
					this.OnRMFCGACCChanging(value);
					this.SendPropertyChanging();
					this._RMFCGACC = value;
					this.SendPropertyChanged("RMFCGACC");
					this.OnRMFCGACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMWRACC", DbType="Int NOT NULL")]
		public int RMWRACC
		{
			get
			{
				return this._RMWRACC;
			}
			set
			{
				if ((this._RMWRACC != value))
				{
					this.OnRMWRACCChanging(value);
					this.SendPropertyChanging();
					this._RMWRACC = value;
					this.SendPropertyChanged("RMWRACC");
					this.OnRMWRACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMSORACC", DbType="Int NOT NULL")]
		public int RMSORACC
		{
			get
			{
				return this._RMSORACC;
			}
			set
			{
				if ((this._RMSORACC != value))
				{
					this.OnRMSORACCChanging(value);
					this.SendPropertyChanging();
					this._RMSORACC = value;
					this.SendPropertyChanged("RMSORACC");
					this.OnRMSORACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRSTINDT", DbType="DateTime NOT NULL")]
		public System.DateTime FRSTINDT
		{
			get
			{
				return this._FRSTINDT;
			}
			set
			{
				if ((this._FRSTINDT != value))
				{
					this.OnFRSTINDTChanging(value);
					this.SendPropertyChanging();
					this._FRSTINDT = value;
					this.SendPropertyChanged("FRSTINDT");
					this.OnFRSTINDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INACTIVE", DbType="TinyInt NOT NULL")]
		public byte INACTIVE
		{
			get
			{
				return this._INACTIVE;
			}
			set
			{
				if ((this._INACTIVE != value))
				{
					this.OnINACTIVEChanging(value);
					this.SendPropertyChanging();
					this._INACTIVE = value;
					this.SendPropertyChanged("INACTIVE");
					this.OnINACTIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOLD", DbType="TinyInt NOT NULL")]
		public byte HOLD
		{
			get
			{
				return this._HOLD;
			}
			set
			{
				if ((this._HOLD != value))
				{
					this.OnHOLDChanging(value);
					this.SendPropertyChanging();
					this._HOLD = value;
					this.SendPropertyChanged("HOLD");
					this.OnHOLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRCARDID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string CRCARDID
		{
			get
			{
				return this._CRCARDID;
			}
			set
			{
				if ((this._CRCARDID != value))
				{
					this.OnCRCARDIDChanging(value);
					this.SendPropertyChanging();
					this._CRCARDID = value;
					this.SendPropertyChanged("CRCARDID");
					this.OnCRCARDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRCRDNUM", DbType="Char(21) NOT NULL", CanBeNull=false)]
		public string CRCRDNUM
		{
			get
			{
				return this._CRCRDNUM;
			}
			set
			{
				if ((this._CRCRDNUM != value))
				{
					this.OnCRCRDNUMChanging(value);
					this.SendPropertyChanging();
					this._CRCRDNUM = value;
					this.SendPropertyChanged("CRCRDNUM");
					this.OnCRCRDNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCRDXPDT", DbType="DateTime NOT NULL")]
		public System.DateTime CCRDXPDT
		{
			get
			{
				return this._CCRDXPDT;
			}
			set
			{
				if ((this._CCRDXPDT != value))
				{
					this.OnCCRDXPDTChanging(value);
					this.SendPropertyChanging();
					this._CCRDXPDT = value;
					this.SendPropertyChanged("CCRDXPDT");
					this.OnCCRDXPDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPDSTHST", DbType="TinyInt NOT NULL")]
		public byte KPDSTHST
		{
			get
			{
				return this._KPDSTHST;
			}
			set
			{
				if ((this._KPDSTHST != value))
				{
					this.OnKPDSTHSTChanging(value);
					this.SendPropertyChanging();
					this._KPDSTHST = value;
					this.SendPropertyChanged("KPDSTHST");
					this.OnKPDSTHSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPCALHST", DbType="TinyInt NOT NULL")]
		public byte KPCALHST
		{
			get
			{
				return this._KPCALHST;
			}
			set
			{
				if ((this._KPCALHST != value))
				{
					this.OnKPCALHSTChanging(value);
					this.SendPropertyChanging();
					this._KPCALHST = value;
					this.SendPropertyChanged("KPCALHST");
					this.OnKPCALHSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPERHIST", DbType="TinyInt NOT NULL")]
		public byte KPERHIST
		{
			get
			{
				return this._KPERHIST;
			}
			set
			{
				if ((this._KPERHIST != value))
				{
					this.OnKPERHISTChanging(value);
					this.SendPropertyChanging();
					this._KPERHIST = value;
					this.SendPropertyChanged("KPERHIST");
					this.OnKPERHISTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPTRXHST", DbType="TinyInt NOT NULL")]
		public byte KPTRXHST
		{
			get
			{
				return this._KPTRXHST;
			}
			set
			{
				if ((this._KPTRXHST != value))
				{
					this.OnKPTRXHSTChanging(value);
					this.SendPropertyChanging();
					this._KPTRXHST = value;
					this.SendPropertyChanged("KPTRXHST");
					this.OnKPTRXHSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTEINDX", DbType="Decimal(19,5) NOT NULL")]
		public decimal NOTEINDX
		{
			get
			{
				return this._NOTEINDX;
			}
			set
			{
				if ((this._NOTEINDX != value))
				{
					this.OnNOTEINDXChanging(value);
					this.SendPropertyChanging();
					this._NOTEINDX = value;
					this.SendPropertyChanged("NOTEINDX");
					this.OnNOTEINDXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATDDT", DbType="DateTime NOT NULL")]
		public System.DateTime CREATDDT
		{
			get
			{
				return this._CREATDDT;
			}
			set
			{
				if ((this._CREATDDT != value))
				{
					this.OnCREATDDTChanging(value);
					this.SendPropertyChanging();
					this._CREATDDT = value;
					this.SendPropertyChanged("CREATDDT");
					this.OnCREATDDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFDT", DbType="DateTime NOT NULL")]
		public System.DateTime MODIFDT
		{
			get
			{
				return this._MODIFDT;
			}
			set
			{
				if ((this._MODIFDT != value))
				{
					this.OnMODIFDTChanging(value);
					this.SendPropertyChanging();
					this._MODIFDT = value;
					this.SendPropertyChanged("MODIFDT");
					this.OnMODIFDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revalue_Customer", DbType="TinyInt NOT NULL")]
		public byte Revalue_Customer
		{
			get
			{
				return this._Revalue_Customer;
			}
			set
			{
				if ((this._Revalue_Customer != value))
				{
					this.OnRevalue_CustomerChanging(value);
					this.SendPropertyChanging();
					this._Revalue_Customer = value;
					this.SendPropertyChanged("Revalue_Customer");
					this.OnRevalue_CustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_Results_To", DbType="SmallInt NOT NULL")]
		public short Post_Results_To
		{
			get
			{
				return this._Post_Results_To;
			}
			set
			{
				if ((this._Post_Results_To != value))
				{
					this.OnPost_Results_ToChanging(value);
					this.SendPropertyChanging();
					this._Post_Results_To = value;
					this.SendPropertyChanged("Post_Results_To");
					this.OnPost_Results_ToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINCHID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string FINCHID
		{
			get
			{
				return this._FINCHID;
			}
			set
			{
				if ((this._FINCHID != value))
				{
					this.OnFINCHIDChanging(value);
					this.SendPropertyChanging();
					this._FINCHID = value;
					this.SendPropertyChanged("FINCHID");
					this.OnFINCHIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOVCRPID", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string GOVCRPID
		{
			get
			{
				return this._GOVCRPID;
			}
			set
			{
				if ((this._GOVCRPID != value))
				{
					this.OnGOVCRPIDChanging(value);
					this.SendPropertyChanging();
					this._GOVCRPID = value;
					this.SendPropertyChanged("GOVCRPID");
					this.OnGOVCRPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOVINDID", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string GOVINDID
		{
			get
			{
				return this._GOVINDID;
			}
			set
			{
				if ((this._GOVINDID != value))
				{
					this.OnGOVINDIDChanging(value);
					this.SendPropertyChanging();
					this._GOVINDID = value;
					this.SendPropertyChanged("GOVINDID");
					this.OnGOVINDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISGRPER", DbType="SmallInt NOT NULL")]
		public short DISGRPER
		{
			get
			{
				return this._DISGRPER;
			}
			set
			{
				if ((this._DISGRPER != value))
				{
					this.OnDISGRPERChanging(value);
					this.SendPropertyChanging();
					this._DISGRPER = value;
					this.SendPropertyChanged("DISGRPER");
					this.OnDISGRPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUEGRPER", DbType="SmallInt NOT NULL")]
		public short DUEGRPER
		{
			get
			{
				return this._DUEGRPER;
			}
			set
			{
				if ((this._DUEGRPER != value))
				{
					this.OnDUEGRPERChanging(value);
					this.SendPropertyChanging();
					this._DUEGRPER = value;
					this.SendPropertyChanged("DUEGRPER");
					this.OnDUEGRPERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCFMTID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string DOCFMTID
		{
			get
			{
				return this._DOCFMTID;
			}
			set
			{
				if ((this._DOCFMTID != value))
				{
					this.OnDOCFMTIDChanging(value);
					this.SendPropertyChanging();
					this._DOCFMTID = value;
					this.SendPropertyChanged("DOCFMTID");
					this.OnDOCFMTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Email_Statements", DbType="TinyInt NOT NULL")]
		public byte Send_Email_Statements
		{
			get
			{
				return this._Send_Email_Statements;
			}
			set
			{
				if ((this._Send_Email_Statements != value))
				{
					this.OnSend_Email_StatementsChanging(value);
					this.SendPropertyChanging();
					this._Send_Email_Statements = value;
					this.SendPropertyChanged("Send_Email_Statements");
					this.OnSend_Email_StatementsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERLANG", DbType="SmallInt NOT NULL")]
		public short USERLANG
		{
			get
			{
				return this._USERLANG;
			}
			set
			{
				if ((this._USERLANG != value))
				{
					this.OnUSERLANGChanging(value);
					this.SendPropertyChanging();
					this._USERLANG = value;
					this.SendPropertyChanged("USERLANG");
					this.OnUSERLANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSFOINTEGRATIONID", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string GPSFOINTEGRATIONID
		{
			get
			{
				return this._GPSFOINTEGRATIONID;
			}
			set
			{
				if ((this._GPSFOINTEGRATIONID != value))
				{
					this.OnGPSFOINTEGRATIONIDChanging(value);
					this.SendPropertyChanging();
					this._GPSFOINTEGRATIONID = value;
					this.SendPropertyChanged("GPSFOINTEGRATIONID");
					this.OnGPSFOINTEGRATIONIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTEGRATIONSOURCE", DbType="SmallInt NOT NULL")]
		public short INTEGRATIONSOURCE
		{
			get
			{
				return this._INTEGRATIONSOURCE;
			}
			set
			{
				if ((this._INTEGRATIONSOURCE != value))
				{
					this.OnINTEGRATIONSOURCEChanging(value);
					this.SendPropertyChanging();
					this._INTEGRATIONSOURCE = value;
					this.SendPropertyChanged("INTEGRATIONSOURCE");
					this.OnINTEGRATIONSOURCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTEGRATIONID", DbType="Char(31) NOT NULL", CanBeNull=false)]
		public string INTEGRATIONID
		{
			get
			{
				return this._INTEGRATIONID;
			}
			set
			{
				if ((this._INTEGRATIONID != value))
				{
					this.OnINTEGRATIONIDChanging(value);
					this.SendPropertyChanging();
					this._INTEGRATIONID = value;
					this.SendPropertyChanged("INTEGRATIONID");
					this.OnINTEGRATIONIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDERFULFILLDEFAULT", DbType="SmallInt NOT NULL")]
		public short ORDERFULFILLDEFAULT
		{
			get
			{
				return this._ORDERFULFILLDEFAULT;
			}
			set
			{
				if ((this._ORDERFULFILLDEFAULT != value))
				{
					this.OnORDERFULFILLDEFAULTChanging(value);
					this.SendPropertyChanging();
					this._ORDERFULFILLDEFAULT = value;
					this.SendPropertyChanged("ORDERFULFILLDEFAULT");
					this.OnORDERFULFILLDEFAULTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTPRIORITY", DbType="SmallInt NOT NULL")]
		public short CUSTPRIORITY
		{
			get
			{
				return this._CUSTPRIORITY;
			}
			set
			{
				if ((this._CUSTPRIORITY != value))
				{
					this.OnCUSTPRIORITYChanging(value);
					this.SendPropertyChanging();
					this._CUSTPRIORITY = value;
					this.SendPropertyChanged("CUSTPRIORITY");
					this.OnCUSTPRIORITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCode", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string CCode
		{
			get
			{
				return this._CCode;
			}
			set
			{
				if ((this._CCode != value))
				{
					this.OnCCodeChanging(value);
					this.SendPropertyChanging();
					this._CCode = value;
					this.SendPropertyChanged("CCode");
					this.OnCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DECLID", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string DECLID
		{
			get
			{
				return this._DECLID;
			}
			set
			{
				if ((this._DECLID != value))
				{
					this.OnDECLIDChanging(value);
					this.SendPropertyChanging();
					this._DECLID = value;
					this.SendPropertyChanged("DECLID");
					this.OnDECLIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMOvrpymtWrtoffAcctIdx", DbType="Int NOT NULL")]
		public int RMOvrpymtWrtoffAcctIdx
		{
			get
			{
				return this._RMOvrpymtWrtoffAcctIdx;
			}
			set
			{
				if ((this._RMOvrpymtWrtoffAcctIdx != value))
				{
					this.OnRMOvrpymtWrtoffAcctIdxChanging(value);
					this.SendPropertyChanging();
					this._RMOvrpymtWrtoffAcctIdx = value;
					this.SendPropertyChanged("RMOvrpymtWrtoffAcctIdx");
					this.OnRMOvrpymtWrtoffAcctIdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIPCOMPLETE", DbType="TinyInt NOT NULL")]
		public byte SHIPCOMPLETE
		{
			get
			{
				return this._SHIPCOMPLETE;
			}
			set
			{
				if ((this._SHIPCOMPLETE != value))
				{
					this.OnSHIPCOMPLETEChanging(value);
					this.SendPropertyChanging();
					this._SHIPCOMPLETE = value;
					this.SendPropertyChanged("SHIPCOMPLETE");
					this.OnSHIPCOMPLETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CBVAT", DbType="TinyInt NOT NULL")]
		public byte CBVAT
		{
			get
			{
				return this._CBVAT;
			}
			set
			{
				if ((this._CBVAT != value))
				{
					this.OnCBVATChanging(value);
					this.SendPropertyChanging();
					this._CBVAT = value;
					this.SendPropertyChanged("CBVAT");
					this.OnCBVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INCLUDEINDP", DbType="TinyInt NOT NULL")]
		public byte INCLUDEINDP
		{
			get
			{
				return this._INCLUDEINDP;
			}
			set
			{
				if ((this._INCLUDEINDP != value))
				{
					this.OnINCLUDEINDPChanging(value);
					this.SendPropertyChanging();
					this._INCLUDEINDP = value;
					this.SendPropertyChanged("INCLUDEINDP");
					this.OnINCLUDEINDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEX_ROW_TS", DbType="DateTime NOT NULL")]
		public System.DateTime DEX_ROW_TS
		{
			get
			{
				return this._DEX_ROW_TS;
			}
			set
			{
				if ((this._DEX_ROW_TS != value))
				{
					this.OnDEX_ROW_TSChanging(value);
					this.SendPropertyChanging();
					this._DEX_ROW_TS = value;
					this.SendPropertyChanged("DEX_ROW_TS");
					this.OnDEX_ROW_TSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEX_ROW_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int DEX_ROW_ID
		{
			get
			{
				return this._DEX_ROW_ID;
			}
			set
			{
				if ((this._DEX_ROW_ID != value))
				{
					this.OnDEX_ROW_IDChanging(value);
					this.SendPropertyChanging();
					this._DEX_ROW_ID = value;
					this.SendPropertyChanged("DEX_ROW_ID");
					this.OnDEX_ROW_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
