<?xml version="1.0" encoding="utf-8"?><Database Name="D2009" Class="clientDynDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=kasai-dyn\gp2015;Initial Catalog=D2009;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="D2009ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RM00101" Member="RM00101">
    <Type Name="RM00101">
      <Column Name="CUSTNMBR" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CUSTNAME" Type="System.String" DbType="Char(65) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTCLAS" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CPRCSTNM" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CNTCPRSN" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="STMTNAME" Type="System.String" DbType="Char(65) NOT NULL" CanBeNull="false" />
      <Column Name="SHRTNAME" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="ADRSCODE" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="UPSZONE" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SHIPMTHD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TAXSCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS1" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS2" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS3" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTRY" Type="System.String" DbType="Char(61) NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="Char(35) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="Char(29) NOT NULL" CanBeNull="false" />
      <Column Name="ZIP" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE3" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="FAX" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="PRBTADCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="PRSTADCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="STADDRCD" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="SLPRSNID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CHEKBKID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="PYMTRMID" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTAMT" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTPER" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CRLMTPAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CURNCYID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="RATETPID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTDISC" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PRCLEVEL" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="MINPYTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MINPYDLR" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="MINPYPCT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FNCHATYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FNCHPCNT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FINCHDLR" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="MXWOFTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MXWROFAM" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="COMMENT1" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="COMMENT2" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="USERDEF1" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="USERDEF2" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="TAXEXMT1" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TAXEXMT2" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="TXRGNNUM" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="BALNCTYP" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="STMTCYCL" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="BANKNAME" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="BNKBRNCH" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="SALSTERR" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="DEFCACTY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RMCSHACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMARACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMSLSACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMIVACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMCOSACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMTAKACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMAVACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMFCGACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMWRACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RMSORACC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FRSTINDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="INACTIVE" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="HOLD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CRCARDID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="CRCRDNUM" Type="System.String" DbType="Char(21) NOT NULL" CanBeNull="false" />
      <Column Name="CCRDXPDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KPDSTHST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="KPCALHST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="KPERHIST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="KPTRXHST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="NOTEINDX" Type="System.Decimal" DbType="Decimal(19,5) NOT NULL" CanBeNull="false" />
      <Column Name="CREATDDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Revalue_Customer" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Post_Results_To" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FINCHID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="GOVCRPID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="GOVINDID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="DISGRPER" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DUEGRPER" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DOCFMTID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="Send_Email_Statements" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="USERLANG" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="GPSFOINTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONSOURCE" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="INTEGRATIONID" Type="System.String" DbType="Char(31) NOT NULL" CanBeNull="false" />
      <Column Name="ORDERFULFILLDEFAULT" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CUSTPRIORITY" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CCode" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="DECLID" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="RMOvrpymtWrtoffAcctIdx" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SHIPCOMPLETE" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CBVAT" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="INCLUDEINDP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_TS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DEX_ROW_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>